# Generated by Django 3.1.3 on 2020-12-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
