# Generated by Django 3.2 on 2021-05-18 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('stripe_id', models.CharField(blank=True, help_text="The product's Stripe Price ID", max_length=100)),
                ('image', models.ImageField(null=True, upload_to='product_images')),
                ('zip_file', models.FileField(null=True, upload_to='product_files')),
                ('description', models.TextField(blank=True, null=True)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False, help_text='Display product on the homepage')),
                ('archived', models.BooleanField(default=False, help_text='Hide product from all listings to prevent new subscribers while keeping current ones.')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
