# Generated by Django 3.2 on 2021-05-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('HOME', 'Home Page'), ('ABOUT', 'About Page'), ('FAQ', 'FAQ'), ('LIST', 'Product List Page'), ('TERMS', 'Terms of Service'), ('PRIVACY', 'Privacy Policy')], default='HOME', max_length=7)),
                ('type', models.CharField(choices=[('H1', 'Heading 1'), ('H2', 'Heading 2')], default='H1', max_length=2)),
                ('heading', models.CharField(max_length=254)),
                ('details', models.TextField(blank=True, help_text='Add some details as a paragraph under the heading', null=True)),
            ],
            options={
                'verbose_name_plural': 'Website Content',
            },
        ),
        migrations.CreateModel(
            name='DisplayPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('ABOUT', 'About Page'), ('FAQ', 'FAQ')], max_length=7)),
                ('navbar_label', models.CharField(blank=True, max_length=50, null=True)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MAIN', 'Main Homepage Image'), ('ABOUT', 'About Page Image'), ('ICON', 'Site Icon'), ('A_ICON', 'Apple Icon'), ('LOGO', 'Navbar Logo')], default='MAIN', max_length=6, unique=True)),
                ('image', models.ImageField(null=True, upload_to='website_images')),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('HOME', 'Home Page'), ('ABOUT', 'About Page'), ('FAQ', 'FAQ')], default='HOME', max_length=7, unique=True)),
                ('title', models.CharField(blank=True, help_text='This will display on the browser tab', max_length=50, null=True)),
                ('description', models.CharField(blank=True, help_text='This will display a text preview in internet search results', max_length=250, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Enter keywords separated by a comma. (Example: subscription website, affordable)', null=True)),
            ],
            options={
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FB', 'Facebook'), ('IG', 'Instagram'), ('PIN', 'Pinterest'), ('TW', 'Twitter')], default='FB', max_length=3, unique=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NAVBAR', 'Navbar'), ('FOOTER', 'Footer')], max_length=6, unique=True)),
                ('text_color', models.CharField(choices=[('LIGHT', 'light'), ('DARK', 'dark')], max_length=5)),
                ('background_color', models.CharField(help_text='Enter a valid hex code. (Example: #301934)', max_length=20)),
            ],
        ),
    ]
