# Generated by Django 3.2 on 2021-06-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_displaypage_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaypage',
            name='page',
            field=models.CharField(choices=[('ABOUT', 'About Page'), ('FAQ', 'FAQ')], max_length=7),
        ),
        migrations.AlterField(
            model_name='seo',
            name='page',
            field=models.CharField(choices=[('HOME', 'Home Page'), ('ABOUT', 'About Page'), ('FAQ', 'FAQ'), ('LIST', 'Product List Page')], default='HOME', max_length=7, unique=True),
        ),
    ]
